import { Roboto } from "next/font/google";
import "./globals.css";
import {AppProvider} from "../components/AppContext"


import Header from "../components/Header";
import Footer from "../components/Footer";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight:['400','500','700'] });

export const metadata = {
  title: "SpicyBites | Food delivery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
       <link rel="icon" href="/chili-pepper.png" sizes="any" />
      <body className={roboto.className}>
        <AppProvider>
        <main className=" mx-auto w-full ">
          <Toaster/>
       <Header/>
        {children}
        <Footer/>
        {/* </Toaster> */}
        </main>
        </AppProvider>
        </body>
    </html>
  );
}
