import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const roboto = Roboto({ subsets: ["latin"], weight:['400','500','700'] });

export const metadata = {
  title: "SpicyBites | Food delivery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <link rel="icon" href="/chili-pepper.png" sizes="any" />
      <body className={roboto.className}>
        <main className=" mx-auto w-full ">
          <Header/>
        {children}
        <Footer/>
        </main>
        </body>
    </html>
  );
}
